variable "env" {}
variable "project_name" {}
variable "table_name" {}
variable "function_name" {}
variable "runtime" {}
variable "handler" {}
variable "filename" {}
variable "memory_size" {}
variable "timeout" {}