name: Terraform CI/CD

on:
  push:
    branches:
      - main       # mainブランチにpushされたとき
  pull_request:
    branches:
      - main       # main向けPR作成時

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init

      - name: Terraform Plan (PR / push)
        working-directory: terraform/envs/dev
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply (main only)
        if: github.ref == 'refs/heads/main'
        working-directory: terraform/envs/dev
        run: terraform apply -auto-approve -var-file="terraform.tfvars"